version: '2.1'

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.17.0
    steps:
      - checkout
      - run: 
          name: Install kubectl
          command: |
            sudo snap install kubectl --classic
      - run: 
          name: Install kind
          command: |
            go get sigs.k8s.io/kind
      - run: 
          name: Go mod download and go tidy
          command: make setup
      - run: 
          name: Run tests
          environment:
            USE_KIND: "true"
          command: make test

workflows:
  version: 2
  deploy_infra_and_test:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true

      - hold-apply:
          type: approval
          requires:
            - terraform/plan

      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply

      - test:
          requires:
            - terraform/apply
