version: '2.1'

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  deploy_infra:
    jobs:
      - terraform/init:
          context: terraform

      - hold-apply:
          type: approval
          requires:
            - terraform/init

      - terraform/destroy:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply
