version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: sanjaypramod/runner
    steps:
      - run: echo "Hi I'm on a Container Runner!"

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  build-workflow:
    jobs:
      - build

  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true

      - hold-apply:
          type: approval
          requires:
            - terraform/plan

      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply
