version: '2.1'

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  kube_audit:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y curl git
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install Go and kind
          command: |
            sudo apt-get update && sudo apt-get install -y golang-go
            GO111MODULE="on" go get sigs.k8s.io/kind@v0.11.1
      - run:
          name: Setup and Install KubeAudit
          command: |
            curl -L "https://github.com/Shopify/kubeaudit/releases/download/v0.14.0/kubeaudit_0.14.0_linux_amd64.tar.gz" -o kubeaudit.tar.gz
            tar -xzf kubeaudit.tar.gz
            sudo mv kubeaudit /usr/local/bin/
            sudo chmod +x /usr/local/bin/kubeaudit
      - run:
          name: Run KubeAudit
          command: |
            kubeaudit version
            # Add more kubeaudit commands as needed

  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      # Add the steps for the 'test' job here, similar to the 'kube_audit' job.

workflows:
  version: 2
  deploy_infra_and_test:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
      - kube_audit:
          requires:
            - terraform/plan
      - hold-apply:
          type: approval
          requires:
            - kube_audit
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply
      - test:
          requires:
            - terraform/apply
