version: 2.1

jobs:
  install_kube_audit:
    docker:
      - image: cimg/base:current
    resource_class: sanjaypramod/runner
    steps:
      # Install kube-audit
      - run: |
          wget https://github.com/Shopify/kubeaudit/releases/download/v0.15.0/kubeaudit_0.15.0_linux_amd64.tar.gz
          tar -xzvf kubeaudit_0.15.0_linux_amd64.tar.gz
          sudo mv kubeaudit /usr/local/bin/
          kube-audit setup  # Example command to set up kube-audit
        name: Install kube-audit

  build:
    docker:
      - image: cimg/base:current
    resource_class: sanjaypramod/runner
    steps:
      - run: echo "Hi I'm on a Container Runner!"

  deploy_infra:
    docker:
      - image: cimg/base:current
    resource_class: sanjaypramod/runner
    steps:
      - checkout
      - terraform/validate:
          context: terraform
      - terraform/plan:
          context: terraform
          persist-workspace: true
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          context: terraform
          attach-workspace: true
          filters:
            branches:
              only: master

workflows:
  build-workflow:
    jobs:
      - install_kube_audit
      - build
      - deploy_infra:
          requires:
            - install_kube_audit
